# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'xitara.voodooforms::lang.models.form.label'

# Model Form Field configuration
form: $/xitara/voodooforms/models/form/fields.yaml

# Model Class name
modelClass: Xitara\VoodooForms\Models\Form

# Default redirect location
defaultRedirect: xitara/voodooforms/forms

# Create page
create:
    title: backend::lang.form.create_title
    redirect: xitara/voodooforms/forms/update/:id
    redirectClose: xitara/voodooforms/forms

# Update page
update:
    title: backend::lang.form.update_title
    redirect: xitara/voodooforms/forms
    redirectClose: xitara/voodooforms/forms

# Preview page
preview:
    title: backend::lang.form.preview_title
